using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Problem2_
{
     class Problem2
    {
        static void Main(string[] args)
        {
            /*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            */
            ulong a = 1; ulong b = 1; ulong c = 0; ulong sum = 0;
            for (ulong i = 0; i < 100; i++)
            {
                a = b; b = c; c = a + b; 
                if (c <= 4000000) {if (c % 2 == 0) {sum = sum + c;Console.WriteLine(sum);}}              
            }
            // Answer: 4613732
        }
    }
}
